name: Categorization

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.event_name }}-${{ github.repository }}-${{ github.ref }}

jobs:
  Update-Categorization-Files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: pip install financedatabase
      - name: Update categories
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import financedatabase as fd
            import pandas as pd

            equities = fd.Equities()
            pd.Series(equities.options('country')).to_csv('Database/Categories/equities_countries.csv', index=False, header=False)
            pd.Series(equities.options('sector')).to_csv('Database/Categories/equities_sectors.csv', index=False, header=False)
            pd.Series(equities.options('industry_group')).to_csv('Database/Categories/equities_industry_groups.csv', index=False, header=False)
            pd.Series(equities.options('industry')).to_csv('Database/Categories/equities_industries.csv', index=False, header=False)

            etfs = fd.ETFs()
            pd.Series(etfs.options('category_group')).to_csv('Database/Categories/etfs_category_group.csv', index=False, header=False)
            pd.Series(etfs.options('category')).to_csv('Database/Categories/etfs_category.csv', index=False, header=False)
            pd.Series(etfs.options('family')).to_csv('Database/Categories/etfs_family.csv', index=False, header=False)

            funds = fd.Funds()
            pd.Series(funds.options('category_group')).to_csv('Database/Categories/funds_category_group.csv', index=False, header=False)
            pd.Series(funds.options('category')).to_csv('Database/Categories/funds_category.csv', index=False, header=False)
            pd.Series(funds.options('family')).to_csv('Database/Categories/funds_family.csv', index=False, header=False)
      - name: Commit files and log
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git checkout main
          git diff-index --quiet HEAD || git commit -am "Update Categorization Files"
          git push
      - name: Check run status
        if: steps.run.outputs.status != '0'
        run: exit "${{ steps.run.outputs.status }}"



