name: Categorization

on:
  push:
    branches:
      - 'main'

jobs:
  Update-Categorization-Files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: pull changes
        run: git pull https://${{secrets.PAT}}@github.com/JerBouma/FinanceDatabase.git main
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: pip install financedatabase
      - name: Update categories
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import financedatabase as fd
            import pandas as pd

            cryptos = pd.read_csv("database/cryptos.csv", index_col=0)
            cryptos_categories = {}
            for column in cryptos:
                if column in ['name', 'summary']:
                    continue
                    
                cryptos_categories[column] = cryptos[column].dropna().unique()
                cryptos_categories[column].sort()
                
            df_temp = pd.DataFrame.from_dict(cryptos_categories, orient='index').reset_index()
            df_temp.to_csv('compression/categories/cryptos_categories.gzip', index=False, compression='gzip')
                
            currencies = pd.read_csv("database/currencies.csv", index_col=0)
            currencies_categories = {}
            for column in currencies:
                if column in ['name']:
                    continue

                currencies_categories[column] = currencies[column].dropna().unique()
                currencies_categories[column].sort()

            df_temp = pd.DataFrame.from_dict(currencies_categories, orient='index').reset_index()
            df_temp.to_csv('compression/categories/currencies_categories.gzip', index=False, compression='gzip')
                
            equities =  pd.read_csv("database/equities.csv", index_col=0)
            equities_categories = {}
            for column in equities:
                if column in ['name', 'summary', 'website']:
                    continue
                    
                equities_categories[column] = equities[column].dropna().unique()
                equities_categories[column].sort()
                
            df_temp = pd.DataFrame.from_dict(equities_categories, orient='index').reset_index()
            df_temp.to_csv('compression/categories/equities_categories.gzip', index=False, compression='gzip')
                
            etfs = pd.read_csv("database/etfs.csv", index_col=0)
            etfs_categories = {}
            for column in etfs:
                if column in ['name', 'summary']:
                    continue
                    
                etfs_categories[column] = etfs[column].dropna().unique()
                etfs_categories[column].sort()

            df_temp = pd.DataFrame.from_dict(etfs_categories, orient='index').reset_index()
            df_temp.to_csv('compression/categories/etfs_categories.gzip', index=False, compression='gzip')
                
            funds = pd.read_csv("database/funds.csv", index_col=0)
            funds_categories = {}
            for column in funds:
                if column in ['name', 'summary', 'manager_name', 'manager_bio']:
                    continue
                    
                funds_categories[column] = funds[column].dropna().unique()
                funds_categories[column].sort()
                
            df_temp = pd.DataFrame.from_dict(funds_categories, orient='index').reset_index()
            df_temp.to_csv('compression/categories/funds_categories.gzip', index=False, compression='gzip')
                
            indices = pd.read_csv("database/indices.csv", index_col=0)
            indices_categories = {}
            for column in indices:
                if column in ['name']:
                    continue
                    
                indices_categories[column] = indices[column].dropna().unique()
                indices_categories[column].sort()
                
            df_temp = pd.DataFrame.from_dict(indices_categories, orient='index').reset_index()
            df_temp.to_csv('compression/categories/indices_categories.gzip', index=False, compression='gzip')
                
            moneymarkets = pd.read_csv("database/moneymarkets.csv", index_col=0)
            moneymarkets_categories = {}
            for column in moneymarkets:
                if column in ['name']:
                    continue
                    
                moneymarkets_categories[column] = moneymarkets[column].dropna().unique()
                moneymarkets_categories[column].sort()
                
            df_temp = pd.DataFrame.from_dict(moneymarkets_categories, orient='index').reset_index()
            df_temp.to_csv('compression/categories/moneymarkets_categories.gzip', index=False, compression='gzip')
      - name: Commit files and log
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git checkout main
          git diff-index --quiet HEAD || git commit -am "Update Categorization Files"
          git push
      - name: Check run status
        if: steps.run.outputs.status != '0'
        run: exit "${{ steps.run.outputs.status }}"



