name: Categorization

on:
  pull_request:
    types: [opened, synchronize, edited]
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.event_name }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import financedatabase as fd

            equities = fd.Equities()
            equities.show_options('countries').to_csv('Database/Categories/equities_countries.csv')
            equities.show_options('sectors').to_csv('Database/Categories/equities_sectors.csv')
            equities.show_options('industry_groups').to_csv('Database/Categories/equities_industry_groups.csv')
            equities.show_options('industries').to_csv('Database/Categories/equities_industries.csv')

            etfs = fd.ETFs()
            etfs.show_options('category_group').to_csv('Database/Categories/etfs_category_group.csv')
            etfs.show_options('category').to_csv('Database/Categories/etfs_category.csv')
            etfs.show_options('family').to_csv('Database/Categories/etfs_family.csv')

            funds = fd.Funds()
            funds.show_options('category_group').to_csv('Database/Categories/funds_category_group.csv')
            funds.show_options('category').to_csv('Database/Categories/funds_category.csv')
            funds.show_options('family').to_csv('Database/Categories/funds_family.csv')
      name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}