name: Compression

on:
  push:
    branches:
      - 'main'

jobs:
  Update-Compression-Files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run : pip install openpyxl
      - run: pip install financedatabase
      - name: Update Compressions
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import financedatabase as fd
            import pandas as pd

            with open('compression/categories/funds_categories.pickle', 'wb') as handle:
                pickle.dump(funds_categories, handle, protocol=pickle.HIGHEST_PROTOCOL)
                
            indices = fd.Indices()
            indices_categories = {}
            for column in indices.data:
                if column in ['name']:
                    continue
                    
                indices_categories[column] = list(indices.data[column].dropna().unique())
                
            with open('compression/categories/indices_categories.pickle', 'wb') as handle:
                pickle.dump(indices_categories, handle, protocol=pickle.HIGHEST_PROTOCOL)
                
            moneymarkets = fd.Moneymarkets()
            moneymarkets_categories = {}
            for column in moneymarkets.data:
                if column in ['name']:
                    continue
                    
                moneymarkets_categories[column] = list(moneymarkets.data[column].dropna().unique())
                
            with open('compression/categories/moneymarkets_categories.pickle', 'wb') as handle:
                pickle.dump(moneymarkets_categories, handle, protocol=pickle.HIGHEST_PROTOCOL)
      - name: Commit files and log
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git checkout main
          git diff-index --quiet HEAD || git commit -am "Update Compression Files"
          git push
      - name: Check run status
        if: steps.run.outputs.status != '0'
        run: exit "${{ steps.run.outputs.status }}"



